#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/common.sh"

CONFIG_PATH="${1:-$ROOT_DIR/environments/dev/config.env}"
RUN_ID="${2:-$(date -u +%Y%m%dT%H%M%SZ)}"

load_config "$CONFIG_PATH"

STATE_DIR="$ROOT_DIR/state/$RUN_ID"
mkdir -p "$STATE_DIR"

REPORT_PATH="$STATE_DIR/run-report.md"

cat >"$REPORT_PATH" <<EOF
# k0rdent deployment report

- run_id: $RUN_ID
- environment config: $CONFIG_PATH
- context: $KUBECONFIG_CONTEXT
- lock file: $LOCK_FILE
- components: kcm, ksm, k0rdent-ui
- excluded: kof

## Notes

Generated by scripts/report.sh after pipeline execution.
EOF

log "Wrote report: $REPORT_PATH"
